### ISSUE TITLE
[Wiki] No se encuentra script para instalar el entorno de desarrollo manualmente

### ISSUE THREAD

**Issue by mredigonda** [omegaup/omegaup#1751] opened 2018-02-15 14:46 UTC
Al parecer, la siguiente página de la wiki está un poco desactualizada: [Cómo empezar a desarrollar entorno manual](https://github.com/omegaup/omegaup/wiki/C%C3%B3mo-empezar-a-desarrollar---entorno-manual).

El comando:
`wget --no-check-certificate https://raw.github.com/omegaup/omegaup/master/stuff/install.sh`
No está funcionando debido a que no existe `install.sh` en la carpeta stuff del repositorio.

Asumo que el script habrá sido movido o renombrado.

**Comment by jaykay12** [comment] 2018-02-16 08:39
@mredigonda Are you able to build omegaUp anyhow?
Yeah, the file `install.sh` is no where to be found in the stuff folder.
I have tried the recommended method of using Vagrant as well as the 3rd method also, but all in vain.
@heduenas Kindly help us through the build process?

**Comment by mredigonda** [comment] 2018-02-16 19:51
Sadly no. I couldn't use Vagrant to install but I assume it has to do more with my lack of proper hardware, Vagrant works fine but in some step of the process it freezes my computer.

**Comment by heduenas** [comment] 2018-02-16 21:09
The vagrant method shusually works pretty smoothly. Please file a bug to https://github.com/omegaup/deploy/issues with the reproduction steps and the error message you get and we'll follow up there.

**Comment by lhchavez** [comment] 2018-02-17 02:58
The issue was fixed by https://github.com/omegaup/deploy/pull/10 \o/

I'll update the wiki to remove the references to the script and marking the whole manual instructions as not to be used due to bitrot :(

**Closed by lhchavez** 2018-02-17 02:58 UTC
