### ISSUE TITLE
[FEATURE] Vueification Contest: contest.new.tpl

### ISSUE THREAD

**Issue by lhchavez** [omegaup/omegaup#3682] opened 2020-04-06 03:05 UTC
Smarty template `contest.new.tpl` needs to be converted to .vue

Please see: [link](https://pastebin.com/5psKRQpH)
Ref: [Master issue](https://github.com/omegaup/omegaup/issues/2009)

**Comment by pabo99** [comment] 2020-05-21 01:10
Dupe of: #3925 

This issue can be closed.

**Closed** 2020-05-21 02:31 UTC
Labels: UI Task, feature-request, refactor
