### ISSUE TITLE
[BUG] Página de "Contest" envía error confuso despues de tratar de crear contest

### ISSUE THREAD

**Issue by pacopedraza** [omegaup/omegaup#1113] opened 2017-02-25 21:05 UTC
1. Entra a omega up
2. Logeate
3. Click en contests
4. Selecciona crear new contest
5. Llena los campos 
6. Click en Schedule contest

RESULTADO ACTUAL:
La página envía el siguiente error: " Parameter can only contain letters, digits, and _.: alias"
No es claro a cual parametro se refiere. 
NOTA: Pude seleccionar una fecha anterior a la de hoy para el contest ( Que no deberia), pero no pude validar si si la registra o no dado el error de parámetro.
![contest_omegaup](https://cloud.githubusercontent.com/assets/11931152/23334782/b08e4c2a-fb6b-11e6-9a7e-097027586ff0.png)

**Comment by joemmanuel** [comment] 2017-02-26 14:42
Thx, +1, `alias` se pierde con los símbolos del final (mi cerebro dejó de parsear después del and). Sugiero que digamos explícitamente que no puede contener espacios y en vez de alias pongamos "Short title" o ambos.

**Comment by lhchavez** [comment] 2017-02-26 14:48
se complica con la traducción :( pero de acuerdo que estaría chido :P

**Comment by Prabhat-10m01** [comment] 2022-04-13 13:42
Can you please assign me this issue?

i will be able to solve it.

**Comment by heduenas** [comment] 2022-04-14 00:12
Hi Prbhat, can you first solve 2 of 3 problems of the phase one test? I have extended the deadline https://omegaup.com/arena/gsoc2022e/

**Comment by Prabhat-10m01** [comment] 2022-04-14 02:57
I will do both things together
Please assign me this issue
Please Please 🙏🙏

**Comment by LuisFer666** [comment] 2022-04-16 16:13
Can you please assign me? I complete phase 1. I'm doing this to complete phase 2

**Comment by heduenas** [comment] 2022-04-16 19:54
Hi LuisFer, can you please confirm your omegaUp username (I couldn't find you as Luis nor Fer)?

**Comment by heduenas** [comment] 2022-04-16 19:57
Is this you? It doesn't say you participated in https://omegaup.com/arena/gsoc2022 nor https://omegaup.com/arena/gsoc2022e

![Screen Shot 2022-04-16 at 12 56 45 PM](https://user-images.githubusercontent.com/597815/163689590-d93806c5-5f2b-4e53-be08-53cd620eea76.png)

**Comment by LuisFer666** [comment] 2022-04-16 20:55
> 

No, this is my account

![image](https://user-images.githubusercontent.com/64329353/163691065-51705463-d700-4b83-a687-b902bf8e98bb.png)

**Comment by ArijeetBanerjee** [comment] 2023-01-23 12:26
Hey there 🙌
It would be an honor to work in this issue
If it is still available, I'd be glad to work in it 💖

**Comment by Yougesh978** [comment] 2023-03-12 20:44
Hello, sir @heduenas is this fix still open? if yes could to assign this to me I have completed the Gsoc test already

**Comment by heduenas** [comment] 2023-03-12 23:44
Done @Yougesh978 !

**Comment by Yougesh978** [comment] 2023-03-13 12:54
hi sir, I wanted to get clarity about the question, So the issue is we have to avoid the selection of prior dates in the calendar of contest selection. Is it correct?

**Comment by tvanessa** [comment] 2023-03-13 19:37
> @heduenas The error message suggests that there is an issue with the "alias" parameter, which should only contain letters, digits, and underscores. To solve this issue, we should check the value that you entered for the "alias" parameter and make sure it only contains these characters. Is my intuition correct ?

No, the solution is to provide a clearer text in the banner. So you need to update the strings/format used.

My suggestion is to change the format; first show the affected parameter, then the error.
For example:

EN: `Alias: Parameter can only contain letters, digits, and "_" character.`
ES: `Alias: El parámetro solo puede tener letras, dígitos y el carácter "_"`

**Comment by axsseldz** [comment] 2024-02-08 01:57
Holaa, si alguien aun no esta asignado/trabajando en este issue, yo podria comezarlo

**Comment by Aritra8438** [comment] 2024-03-20 08:11
So, I completed step 1.
Can you please assign this issue to me?

Thanks.

**Comment by pabo99** [comment] 2024-03-20 08:18
> So, I completed step 1. Can you please assign this issue to me?
> 
> Thanks.

Done!

**Comment by Aritra8438** [comment] 2024-03-21 20:01
Hi @pabo99, as @tvanessa suggested, I changed the order of the affected parameter and the error. 
PTAL!

**Closed** 2024-03-25 17:00 UTC
Labels: P2, 2 hours, omegaUp for Contests, bug, Good first issue
