### ISSUE TITLE
Como administrador de concursos y cursos de la OMI/P/S, quiero poder exportar la lista de usuarios que lo presentan para poder obtener su información como nombre, email, estado, escuela, para tener el contexto completo.

### ISSUE THREAD

**Issue by andreasantillana** [omegaup/omegaup#1678] opened 2018-01-15 02:31 UTC
## Comportamiento Esperado
Que exista un lugar en el sitio donde se pueda pedir que se exporte la lista de alumnos y descargue un csv, o algo así.

## Comportamiento Actual
Ahorita no hay forma de acceder a esos sin que Chávez me ayude :(

## Posible Solución
Creo que podría ser desde la vista de lista de los concursos. Agregar una columna donde están los botones de links a scoreboards y ver eventos del concurso, etc.

## Contexto
Queremos que los alumnos de la OMIPS puedan crecer usando omegaUp a pesar de no tener entrenador o que no de el nivel, para esto estamos generando cursos y concursos para que los alumnos entrenen. Pero para las siguientes fases, para poder canalizarlo con su delegado necesitamos saber otros datos del usuario y no solo su username.

Gracias 💜

**Comment by lhchavez** [comment] 2018-01-17 01:12
Este cambio necesita una opción para que los organizadores elijan que necesitan esta información de los concursantes, y los concursantes deberían ver un disclaimer que esa información se le va a compartir a los organizadores.

También necesitamos una vista o un descargador de .csv para eso.

**Comment by elendil326** [comment] 2018-02-14 01:46
Requiere #1688 primero

**Comment by AtharvaKhare** [comment] 2018-02-23 03:26
@lhchavez Can I take this one please?
If so,
1. Can you please elaborate the deliverables?
2. We can have two approaches:
   a - "Hide profile from public" option prevents user from appearing in the list. This would be inconvenient to users.
   b - User is asked to share information per contest basis. I think this would need separate column/table in the database.
3. Where exactly should be the option to export the list of students?

**Comment by lhchavez** [comment] 2018-02-23 05:06
Of course! Your proposal 2b. matches what we were thinking was the most convenient solution, so let's go with that one.

What we need to do is add a flag to the [`Problemsets`](https://github.com/omegaup/omegaup/blob/8c21617376773f9d2b9412eb04c26559233d4bb9/frontend/database/schema.sql#L511) (which is the generalization of Contests and Homeworks/Assignments for Courses) and [`Courses`](https://github.com/omegaup/omegaup/blob/8c21617376773f9d2b9412eb04c26559233d4bb9/frontend/database/schema.sql#L160) (which is a bit denormalized for making it easier to query) tables that says that users that want to participate in the contest/course need to consent to having a subset of their information be disclosed to the organizer. This flag should be modifiable through the [Edit Contest](https://github.com/omegaup/omegaup/blob/master/frontend/templates/contest.edit.tpl) page, probably here:

![image](https://user-images.githubusercontent.com/168028/36578282-fa5b559c-1810-11e8-9695-8fa10caf681f.png)

That would need to be changed in [`ContestController.php`](https://github.com/omegaup/omegaup/blob/master/frontend/server/controllers/ContestController.php), in both the [`apiCreate`](https://github.com/omegaup/omegaup/blob/8c21617376773f9d2b9412eb04c26559233d4bb9/frontend/server/controllers/ContestController.php#L819) and [`apiUpdate`](https://github.com/omegaup/omegaup/blob/8c21617376773f9d2b9412eb04c26559233d4bb9/frontend/server/controllers/ContestController.php#L2083) methods. A similar set of changes would be required for the CourseController.

Then the unit tests for that (which should be failrly straightforward).

Finally all the various UI components would need to be updated. Here's a similar [PR](https://github.com/omegaup/omegaup/pull/1661/files) that just asked the users to fill out their profiles prior to starting the contest, but it touched roughly the same places of the code that this would need to touch.

Finally for the option to export the list of students, we can make the API return a normal JSON for consistency and then from the JavaScript side construct the .csv that can be downloaded. We already do that to export the [students' progress in courses](https://github.com/omegaup/omegaup/blob/2d85e2d471f999291dbca2e53ffbe176a8e03810/frontend/www/js/omegaup/components/course/ViewProgress.vue#L67), so if we want to go through that route, we'll need to do a refactor to move those functions to another file to avoid code repetition.

Feel free to split the change into several pieces (some suggestions: controllers+tests first, UI later. or all the contest first, courses later). This one in particular is not a huge change, so given that the cost of reviewing it all at once is not excessive, it's also fine if you want to solve it in one go. Whatever is most convenient for you :)

And as always, feel free to ask more questions.

**Comment by lhchavez** [comment] 2018-02-24 01:56
Welp, there was a large internal miscommunication and there was another issue that was a near-duplicate of this one https://github.com/omegaup/omegaup/issues/1742 D: There's even a pull request open for it :( https://github.com/omegaup/omegaup/pull/1776

So the scope of this particular issue has been reduced to only do API that can return the list of users that have given permission and the CSV exporter. We have two options here:

* Cherry-pick https://github.com/omegaup/omegaup/pull/1776 and try to build the feature on top of it.
* Wait until that other thing is merged.

Which one do you prefer?

And going forward, the attendees of the triage meetings will have to be more careful spotting duplicates to avoid this kind of issues :(

**Comment by AtharvaKhare** [comment] 2018-02-24 06:24
Ah, no problem! I might wait till its merge, is that fine?
Till then I will search if I can do any other issue.

**Comment by lhchavez** [comment] 2018-02-24 22:11
yes, totally fine. i expect to be able to merge it on Tuesday/Wednesday.

**Comment by elendil326** [comment] 2018-09-28 16:08
Hey @AtharvaKhare, I see #1776 has merged. Do you think you will have a chance to complete this part? Or should I assign it to someone else?

**Comment by AtharvaKhare** [comment] 2018-09-29 04:34
Hi @elendil326 , I am sorry, I forgot that I had been assigned this issue. I am working on another issue right now, so its ok to assign it to someone else, thanks.

**Comment by elendil326** [comment] 2018-10-11 23:40
Thanks @AtharvaKhare , I'm moving it into the sprint planning.

**Comment by elendil326** [comment] 2018-10-12 01:19
Se agregará botón para descargar el CSV y el controlador para generarlo.

**Closed** 2019-06-12 13:51 UTC
Labels: 8, API Task, P1, omegaUp For Contests
