### ISSUE TITLE
In the Ranking page (https://omegaup.com/rank/) Next button not working properly

### ISSUE THREAD

**Issue by akki111singh** [omegaup/omegaup#2356] opened 2019-02-01 01:32 UTC
If the user click on the next button at bottom in  https://omegaup.com/rank/ page then after the first and second page directly 21st page is coming and after that no proper paging.

**Comment by lhchavez** [comment] 2019-02-01 04:19
Dupe of #2339

**Closed by lhchavez** 2019-02-01 04:19 UTC
