### ISSUE TITLE
Toaster Error notification does not appear within page fold

### ISSUE THREAD

**Issue by tiqtok** [omegaup/omegaup#1349] opened 2017-07-22 05:10 UTC
## Comportamiento Esperado

*All notifications should appear within a user's page fold so that they immediately know there was an error without having to think to scroll up.*

## Comportamiento Actual

*Toaster notification appears above page fold, and new users may be unaware.*

## Posible Solución

This is a potential work around, although there are more elegant solutions to this problem like allowing the toaster notification to appear above the section where the error occurred (log in vs sign up)
*
Add following to .alert {
    position: sticky;
    top: 60px;
    z-index: 2;
    box-shadow: 0px 0px 1px #ad4d4c;
}
*

## Pasos para reproducir (para bugs)

1. Create new user with password 'test'
2. Notification will appear above the page fold in natural use cases. 

## Contexto

*Took time to realize there was an error with the app itself and not just my computer. Didn't realize a toaster error message was appearing until eventually scrolling up. *

## Tu ambiente

NA

**Comment by lhchavez** [comment] 2017-07-22 05:11
Dupe of https://github.com/omegaup/omegaup/issues/1338

**Closed by lhchavez** 2017-07-22 05:11 UTC
